name 'df_kibana'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures df_kibana'
long_description 'Installs/Configures df_kibana'
version '0.1.0'
